airscript:
  init:
    scripts:
      - samples/rc
  verbose: true
  download-dir: .
  timeout: 20.0
  tls:
    verify: false

servers:
  test:
    - name: test
      hostname: 10.92.0.17
      apikey: eyJlbm...
      mgmt: true
  prod:
    - name: prod1
      hostname: 192.168.200.1
      apikey: eyJlbm...
      peer: prod2
    - name: prod2
      hostname: 192.168.200.2
      apikey: eyJlbm...
      peer: prod1

config-groups:
  prod:
    code: P
    label: prod
    servers:
      - server-name-1
      - server-name-2
    virtual-hosts:
      - www.example.com
      - example.com
      - app.example.com
  test:
    code: T
    label: integration
    servers:
      - server-name-3
      - server-name-4
    virtual-hosts:
      - test.example.com
      - app.test.example.com
